### ISSUE TITLE
系上成員圖片不見了

### ISSUE THREAD

**Issue by jellynina** [jellynina/ide.ncku#14]
1. 框框先統一
2. 把圖的連結修回來

**Comment by jellynina** [comment]
圖的連結已經補回來
框框位置統一
[頁面](http://bgc004.web.ncku.edu.tw/files/90-1417-1.php?Lang=zh-tw)
[codepen](https://codepen.io/jellynina/pen/wqrpKb)

**Comment by elluu** [comment]
ok
兼任老師的部分 我等等會加進老師Email

**Comment by jellynina** [comment]
ＯＫ，知道怎麼加上去嗎？
完成後在這邊說一聲

**Comment by elluu** [comment]
已加上

另外
膺慈表示
雅惠的頭可以不要被打嗎
![2017-12-07 22 11 30](https://user-images.githubusercontent.com/29235418/33719459-c2ad067e-db9b-11e7-8b16-dccfc73c5087.png)

和行政人員四個字太貼邊  要下來一點

**Comment by jellynina** [comment]
噗滋，又被打到了～好～我再條整

**Comment by jellynina** [comment]
調整完畢，關閉議題
