### ISSUE TITLE
上線相關資訊 from 亨亨

### ISSUE THREAD

**Issue by elluu** [jellynina/ide.ncku#15]
您好!
 
貴單位(工業設計學系)申請之網站管理平台, 已建置完成. 前後台網址如下:
前台網址: http://www.ide.ncku.edu.tw  (英文網頁: http://www.ide.ncku.edu.tw/bin/home.php?Lang=en )
 
請參考網站建置規則: http://web.cc.ncku.edu.tw/files/14-1006-17059,r33-1.php
ePage使用說明請參考: http://web.cc.ncku.edu.tw/files/11-1006-680.php
Banner(單位名稱圖片)須自行修改, 請參考說明: http://web.cc.ncku.edu.tw/files/15-1006-5238,c2405-1.php
 
網站負責人, 請於”成大首頁暨各單位網頁管理”( http://web.cc.ncku.edu.tw ) 網站上註冊會員，
以利後續接收本校網頁相關資訊，或使用有問題時，可於討論區提問．
 
網站內容建置完成後, 欲修改本校中英文首頁之教學單位連結, 請洽計網中心或教處處李蕙年小姐(分機:50119).
 
謝謝!
 
PS:
l 希望網址, 因與貴單位現行網址相同, 故請暫時以下列暫時網址進入建置資料:
http://bg004.web.ncku.edu.tw/admin/
l 待資料建置完成, 欲上線前, 請貴單位申請變更DNS設定 (www.ide.ncku.edu.tw對應IP改為140.116.241.55).
l 並於ePage後台修改預設網址(參數設定->學校資料->網站域名). 且之後勿再使用暫時網址登入後台.

**Comment by jellynina** [comment]
部分資訊敏感，先block起來
這個repo非私密，核心訊息請放到 [jellynina/id.web](https://github.com/jellynina/id.web)

**Comment by jellynina** [comment]
@elluu  能了解一下網域的狀況嗎？

**Comment by elluu** [comment]
好的沒問題

**Comment by elluu** [comment]
@jellynina 關於網域
剛剛有詢問老師網域是否可以與舊網站重新連結，老師回應是因為菁培網站還在舊有網域裡，如果更改可能要一起把菁培網站移動到epage，所以暫時不更動

**Comment by jellynina** [comment]
@elluu 了解了！
