### ISSUE TITLE
系上課程頁面小小問題

### ISSUE THREAD

**Issue by elluu** [jellynina/ide.ncku#19]
![2017-12-26 13 36 40](https://user-images.githubusercontent.com/29235418/34348077-0e9e5a46-ea43-11e7-98b4-fe0819c0e6f8.png)
系上課程的頁面的header 跟其他頁面不太一樣

**Comment by jellynina** [comment]
https://github.com/jellynina/ide.ncku/blob/2b930c50cbbce9ab7ed7aa348d86613fd067600b/vueWorkspace/src/components/CoursePage.vue#L93


頁面內容CSS覆寫了，已修正

**Comment by elluu** [comment]
感謝大神，close issue
