### ISSUE TITLE
系網首頁

### ISSUE THREAD

**Issue by elluu** [jellynina/ide.ncku#20]
用Chrome瀏覽器瀏覽的時候在交通資訊和工廠之間有塊白色的block，想問一下要怎麼辦
![2017-12-26 13 37 48](https://user-images.githubusercontent.com/29235418/34348115-66203ece-ea43-11e7-8c7f-1bcb7db5597d.png)

**Comment by jellynina** [comment]
<img width="1234" alt="2017-12-26 3 27 03" src="https://user-images.githubusercontent.com/6845626/34348911-4522e966-ea51-11e7-9357-781c3f96145d.png">
多放了一個模組，刪掉應該就可以了。
你試試看吧

**Comment by elluu** [comment]
問題解決 close issue
